d_update_clip: .inf
eta: 0.01
in_neurons: 784
input_unit_var: true
input_zero_mean: true
kernel_size: 1
lambda_: 0.05
lca_iters: 1000
metric_fpath: c:\Users\BOKHARS\Desktop\Code\lca-pytorch\examples\mnist_dictionary_learning\metrics.xz
no_time_pad: false
nonneg: true
out_neurons: 1568
pad: valid
req_grad: false
result_dir: c:\Users\BOKHARS\Desktop\Code\lca-pytorch\examples\mnist_dictionary_learning
return_all_ts: false
return_vars:
- inputs
- acts
- recons
- recon_errors
stride: 1
tau: 100
track_metrics: false
transfer_func: soft_threshold
weight_init: trunc_normal_
weight_init_kwargs: {}
